language: go

go:
  - 1.14.x

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

after_success:
  - go test ./... -coverprofile=profile.out -covermode=count
  - PATH=$HOME/gopath/bin:$PATH goveralls -coverprofile=profile.out -service=travis-ci

install:
  - go get -d -v -t ./...

script:
  - go test -race ./...
